---
title: "Wohnungsmigration in München"
author: "Heinz Calderón, Christian Lex, Dennis Ley, Haoyang Yang"
format:
   revealjs:
     theme: [default, customstyle.css]
     transition: slide
     slide-number: c
     logo: "Output/PresentationBilder/LMU_Logo.svg"
editor: visual
---

```{r setup, include=FALSE}
#| include: false
#| message: false
#| warning: false

source("Program/05_visualisierungen_final.R")
```

## Agenda

::: incremental
1.  Datenüberblick

2.  Datenanalyse

    Zuzüge & Umzüge

    Wegzüge

    Bevölkerungsentwicklung

3.  Zusammenfassung
:::

## Datenüberblick

::: incremental
-   25 stadtbezirke

-   Um- Zu- und Abzüge aus München
:::

## Agenda

1.  [Datenüberblick]{style="opacity: 0.25;"}
2.  **Datenanalyse**
    -   Zuzüge & Umzüge

    -   [Wegzüge]{style="opacity: 0.25;"}

    -   [Bevölkerungsentwicklung]{style="opacity: 0.25;"}
3.  [Zusammenfassung]{style="opacity: 0.25;"}

## Zuzüge

```{r plot_zuzuege, fig.align='center', warning=FALSE, message=FALSE, echo=FALSE, fig.width=7, fig.height=4,fig.dpi=300}
plot_zuzuege
```

## Zuzüge
```{r plot_zuzuege_highlight, fig.align='center', warning=FALSE, message=FALSE, echo=FALSE, fig.width=7, fig.height=4,fig.dpi=300}
plot_zuzuege_highlight
```

## Umzüge

```{r plot_umzuege, fig.align='center', warning=FALSE, message=FALSE, echo=FALSE, fig.width=7, fig.height=4,fig.dpi=300}
plot_umzuege
```

## Umzüge

```{r plot_umzuege, fig.align='center', warning=FALSE, message=FALSE, echo=FALSE, fig.width=7, fig.height=4,fig.dpi=300}

```






